version: '3.7'

services:
  piglatinize-service:
    build: ./
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./piglatinize-service/:/app/
    ports:
      - 8001:8000
